build:
  version: "2.0"
accounts:
  message: "Welcome to ICICI Bank Accounts related QA APIs"
  contactDetails:
    name: "Smitha Roy - Developer"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371